version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      typescript-stack:
        patterns:
          - "ts-node"
          - "tsconfig-paths"
          - "typescript"
          - "typescript-compat"
      backend-tooling:
        patterns:
          - "@types/*"
          - "cross-env"
          - "newman"
          - "prettier"
          - "wait-on"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      mantine:
        patterns:
          - "@mantine/*"
      next-stack:
        patterns:
          - "next"
          - "sharp"
      frontend-tooling:
        patterns:
          - "@types/node"
          - "postcss"
          - "postcss-preset-mantine"
          - "prettier"
          - "typescript"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
